### ISSUE TITLE
Playing wav file in recorder.swf?

### ISSUE THREAD

**Issue by tamerzg** [jwagener-soundcloud/recorder.js#1]
What is the parameter to load and play existing wav file in recorder.swf?

**Comment by jwagener** [comment]
currently there is no way to load an existing wav file into the buffer.
why would you want to do that? to mix over a recording?

**Comment by tamerzg** [comment]
I implemented this recorder as part Drupal module, and sometimes there is a case where we have edit page so users can hear already uploaded audio before removing it or overwriting with new recording. I guessed will be able to do that without need of wav player. Also do you know of any wav player to recommend?

**Comment by jwagener** [comment]
ah ok. i would recommend to use soundmanager http://www.schillmania.com/projects/soundmanager2/ or just use the html5 audio tag (if the browser supports it) to playback the existing wav file.
