### ISSUE TITLE
Request permission in advance of recording

### ISSUE THREAD

**Issue by brianchirls** [jwagener-soundcloud/recorder.js#17]
If possible, it would be great to be able to request microphone access permission separately from recording.

In my use case, timing is important so we need to make it very clear to the user when recording starts. We want to have a countdown, similar to how Mac Photobooth has a 3-2-1 before taking a picture. This won't really work if it counts down to a permission request, after which the recording starts immediately and without further warning. Ideally, we can request mic access without recording when the edit module is first loaded up so there's no further interruption.

Thanks.

**Comment by jwagener** [comment]
there is an undocumented call to show the permission dialog: 

Recorder.flashInterface().showFlash()

Guess it's time to make it part of the offical API.

**Comment by brianchirls** [comment]
That's great. Thanks!

I was gonna record and immediately stop as a workaround, but this is _much_ better.
