### ISSUE TITLE
Array loop breaks when loaded with Ember.js

### ISSUE THREAD

**Issue by brianchirls** [jwagener-soundcloud/recorder.js#18]
When Ember.js has the setting "EXTEND_PROTOTYPES", it will modify the global Array prototype, adding properties and methods. `Recorder.triggerEvent` uses a "for..in" loop on the `_event` arrays without checking against `hasOwnProperty` or on the type of every property. So when it tries to call a function that is not really a function, it crashes.

Looping with array indices would solve this problem. It's [faster](http://jsperf.com/fastest-array-loops-in-javascript/18) anyway.

**Comment by jwagener** [comment]
thx!
