### ISSUE TITLE
Flash security box is not hiding if user deny

### ISSUE THREAD

**Issue by peterkr** [jwagener-soundcloud/recorder.js#2]
Hi,

If user deny the access to mic, flash "div" still there. how to trigger hide option if user click deny button.

and other thing there are two flash security windows are opening, while asking for permission? is both required?

Is possible to focus on privacy tab instead of focusing on Microphone volume tab? 

Thanks
Peter

**Comment by peterkr** [comment]
I can hide this at record callback "start" function. but for deny how can I hide this?

And how can I change focus on tab by default to "privacy"

**Comment by jumptrnr** [comment]
@peterkr 

"And how can I change focus on tab by default to "privacy"

-ever figure that out?

**Comment by jwagener** [comment]
the latest update fixes the flash hiding issue finally. sorry for being so late/lame :/ showing the privacy tab is not possible yet.
