### ISSUE TITLE
Flash issues?

### ISSUE THREAD

**Issue by tamerzg** [jwagener-soundcloud/recorder.js#3]
Not sure how to describe this issue, it seems something related to the Flash. Sometimes and on multiple browsers (FF, Chrome) the recording gets recorder but like in a very slow mode. When played you will hear noice which sounds like fast forwarding. Also when that happens I noticed that timer is counting very slow so each second seems like 2-3sec. Timer is implemented in progress record callback (same as in your examples). Let me know if you have ever encountered similar problems?

**Comment by jwagener** [comment]
Weird. Didn't happen to me so far, but will have a look into it.
Please let me know if you figure out a way to reproduce it.

**Comment by jwagener** [comment]
was able to reproduce it now, will investigate further how to fix it.

**Comment by tamerzg** [comment]
Let me know if you manage to figure out the solution?

**Comment by tamerzg** [comment]
Hello, any updates?

**Comment by sixtyfive** [comment]
We had something like that, too, every now and then. What is your way to reproduce it, jwagener?

**Comment by lylepratt** [comment]
I experience this every time on my Macbook Air. When playing back the recorded sound, it sounds really sped up like "chipmunk" sound. This separate project seems to have the same issue on my machine:
https://github.com/cykod/FlashWavRecorder

**Comment by lylepratt** [comment]
I've had some more insight into this issue: It only seems to occur when using the built in Mic in my Macbook Air. When I use an external USB Mic, I do not have the issue. I also tested on a Asus Windows laptop and had the same results.

**Comment by lylepratt** [comment]
Any updates on ways to fix the "chipmunk" issue? I'd like to use this in production, but on half of the laptops I try, the sound is sped up tremendously.

**Comment by tamerzg** [comment]
Fixed in https://github.com/jwagener/recorder.js/pull/11
