### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by joekur** [jwagener-soundcloud/recorder.js#7]
Can you give any advice on modifying the source to allow multiple recording instances at once? I would like to record separate snippets of audio without conflict.

**Comment by jwagener** [comment]
hi,

a simple way could be to add a function like

protected var buffers:Array;
function setActiveBuffer(index):void {
  if(!buffers[index]){
   buffers[index] = new ByteArray();
  }

 buffer = buffers[index];
}

and then expose that as well in addExternalInterfaceCallbacks.
