### ISSUE TITLE
this.swfObject.children[3].record is not a function

### ISSUE THREAD

**Issue by Evilcash** [jwagener-soundcloud/recorder.js#9]
Hello, jwagener.
Thank you for such a nice recorder you've made.

I spent a couple of hours to set it to work, but with no luck.
Every time I can't get access Flash functions.

Console thows "TypeError: this.swfObject.children[3].record is not a function".
But swf object is in the DOM and fully accesseble.

How can I fix this?

**Comment by Evilcash** [comment]
Also I've got a "Error calling method on NPObject".

**Comment by jwagener** [comment]
does the test suite on http://recorderjs.ponyho.st/test/test.html run through for you?
If not could you send over some browser/flash/os version details?

**Comment by Evilcash** [comment]
Thank you for the answer, Johannes.
I think, I've screwed up a bit. The problem was in the url for the swf object.
So this problem is resolved.
